### ISSUE TITLE
[rstream] - inconsistent behaviour with metaStream

### ISSUE THREAD

**Issue by allforabit** [thi-ng/umbrella#108]
Hi Karsten, I've playing with the library again after a bit of a break. I'm trying out the `metaStream` feature that was added a few months ago. It looks like it adds a lot of flexibility. I've been experimenting with using like this. I know there isn't any examples of usage like this so maybe it's not intended to be used in the is way! 
```
const delayedStream = n => {
  return stream(o => {
    delayed(2 * n, 1000).then(x => {
      o.next(x);
      o.done();
    });
  });
};

const a = stream()
  .subscribe(metaStream(delayedStream));

a.next(99);
```

So this would generate a stream for each value coming in. Obviously this is just a toy example but it would be useful to define the behaviour of an app calling a backend for instance. Only the latest request would be kept and all others would be dropped. This works actually. Almost :-)

If I do subscription like this:
```
a.subscribe(trace())
```
I'll get the transformed value from the delayed stream.

However if I chain a subscription directly I'll get the value that was directly sent into a:
```
// Chained sub won't use the delayedStream and instead will output value sent in to a
const a = stream()
  .subscribe(metaStream(delayedStream)).subscribe(trace());
```
I hope this is clear. Let me know if you need any clarification on it. Thanks!

**Comment by postspectacular** [comment]
Hey @allforabit - missed you here! :) I will have to dig into this later (by tomorrow) and can't give you a clear explanation right now, but for now wanted to point you to the doc strings for [`metastream`](https://github.com/thi-ng/umbrella/blob/master/packages/rstream/src/metastream.ts) (only in case you haven't see it)...

**Comment by postspectacular** [comment]
Hey again, so I figured it out and it's actually very simple:

The return value for `a.subscribe(b)` is the value (or a possibly wrapped version of) `b`, not `a`. Likewise, for a chain like `x = a.subscribe(b).subscribe(c)`, the `x` will be the result of the last `subscribe()` (i.e. `c` or a wrapped version of it).

In other words, the confusion here comes from the misinterpretation of your first variation:

```ts
const a = stream().subscribe(metaStream(delayedStream));
```

Here `a` is not the original seed stream, but already the `metaStream` instance. The example still seemingly works, because 1) using `next()` you can inject values at any point in the processing pipeline (as long as you have a handle to it) and 2) there're no other processing steps between `stream()` and the `metaStream` sub...

OTOH, here the issue becomes more obvious:

```ts
const a = stream().transform(map((x)=>x*100)).subscribe(metaStream(delayedStream));

a.next(99);
// 198 (still)

a instanceof MetaStream
// true
```

So I guess, you already can see the solution :) - just split the call chain and assign the right parts to variable(s):

```ts
const a = stream();
a.subscribe(metaStream(delayedStream)).subscribe(trace());

a.next(99);
// 198 (after delay)
```

Makes sense?

**Comment by allforabit** [comment]
Doh! Yes of course, thanks very much for the quick and helpful response :-)

**Comment by postspectacular** [comment]
Pleasure & good luck!

**Comment by postspectacular** [comment]
@allforabit Forgot to mention earlier, you might find this helpful too: https://github.com/thi-ng/umbrella/wiki/rstream-recipes

**Comment by allforabit** [comment]
Ah very nice thanks, I hadn't seen that.
