### ISSUE TITLE
[hdom-canvas] how to set up rotate point

### ISSUE THREAD

**Issue by IvanWoo** [thi-ng/umbrella#131]
Greetings!

I try to rotate a image shape of SVG, the code snippet looks like:

```
[
  "g", {},
  [
    "img",
    {
      rotate: ((Math.cos(now * -0.0005) + Math.PI / 5) % Math.PI) * 4
    },
    circle_0_img,
    [0, 0]
  ]
]
```

I find out the default rotate point is at upper left, but I want to rotate at center of the image.

Based on [this documentation](https://github.com/thi-ng/umbrella/tree/master/packages/hdom-canvas#rotation), the rotate attribute only accept theta as input, which is inconsistent with [the SVG documentation](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform#Rotate).

I also find that we can set rotate point by directly manipulating SVG transform attribute in the [examples/rstream-grid](https://github.com/thi-ng/umbrella/blob/master/examples/rstream-grid/src/dataflow.ts#L74).

I am just wondering if there any API or workaround to set the rotate point for my instance.

Thank you so much.

**Comment by postspectacular** [comment]
Hi @IvanWoo - as much as the hdom-canvas syntax is *inspired* by SVG, it's not a 1:1 correspondence, also largely due to differences & limitations of the underlying HTML canvas API. However, you can achieve rotation around an arbitrary point by wrapping the image in a group element, as [shown in this quick example](https://codesandbox.io/s/cranky-cherry-4d5l9?fontsize=14&module=%2Fsrc%2Findex.ts).

```ts
[
    canvas,
    { width: 200, height: 200 },
    [
        "g",
        { translate: [100, 100], rotate: (Date.now() - t0) * 0.001 },
        ["img", { width: 64, height: 64 }, myImg, [-32, -32]]
    ]
]
```

Also, do checkout these 2 examples, which use a more elaborate scenegraph (and core parts of which are currently in the process of being turned into a [new package](https://github.com/thi-ng/umbrella/tree/feature/scenegraph/packages/scenegraph/src)):

- https://github.com/thi-ng/umbrella/tree/master/examples/scenegraph-image
- https://github.com/thi-ng/umbrella/tree/master/examples/scenegraph

**Comment by postspectacular** [comment]
@IvanWoo - I've just updated the above linked sandbox example to show an alternative solution, not requiring a group:

```ts
[
    "img",
    {
        translate: [100, 100],
        rotate: (Date.now() - t0) * 0.001,
        width: 64,
        height: 64
    },
    img,
    [-32, -32]
]
```

**Comment by IvanWoo** [comment]
@postspectacular - Thanks for the quick reply! The solution is sweet. And I am looking forward the new package : )
