### ISSUE TITLE
Channel.SCHEDULE cpu usage

### ISSUE THREAD

**Issue by pedroteixeira** [thi-ng/umbrella#16]
Hello,

When using `Channel.select` in the browser, I'm noticing high cpu usage. 
Is this "expected" from the library / are there any best practices for this?

I was wondering if `setImmediate` is the way to go on browser environments.
I was hoping that await/async could help on this to avoid pulling..

thanks for the great work!

**Comment by postspectacular** [comment]
Hi @pedroteixeira - thanks - there's actually support for `setImmediate`, but it needs to be provided externally (e.g. it's the default in node or via polyfill). See here: https://github.com/thi-ng/umbrella/blob/master/packages/csp/src/channel.ts#L233

The CPU usage should only be high for ops involving `select()` or `merge()`. I've noticed it too (not just in this implementation), but I just didn't see a way around it apart from increasing the timeout period or maybe adding an additional arg to `select` to make it configurable on a case-by-case basis (i.e. use longer timeout by default, but allow higher throughput if needed).

**Comment by pedroteixeira** [comment]
thanks for explaning, right now I'm considering setting for a browser scope something like this:
`Channel.SCHEDULE = f => setTimeout(f, 1000);`

Perhaps having something like a "onClose promise" could be used to get notified about closed channel. I don't think I had this issue with this other library https://github.com/AppliedMathematicsANU/plexus-csp/ - perhaps can give some ideas :)

**Comment by postspectacular** [comment]
You can do this, but I'd say 1 second is waaayyy too long, for normal use cases at least. You'll then wait at least this long if none of the input channels given to `select` are readable in the first round. A 16ms (or less really) timeout should be sufficient (IMHO) and give you only a single frame delay (if used for UI purposes). Also, thanks for the link to the other lib, will check it out! I only had prior experience with ClojureScript's core.async and that too had similar behavior...

As for the `onclose` promise - that's a good idea, but would not help in this specific case. The issue w/ `select` is that we need to repeatedly poll the input channel's readable & closed flags, but can only read / take a value from the first which becomes available. The high CPU load only happens if all inputs are producing values rather slowly/infrequently and/or a long timeout is used.

In my experience a better approach is to use short timeouts for `select`, and have another timeout in your processing loop, like so. `Channel.timeout`on its own is super cheap (just a promise resolved via native `setTimeout`...

```typescript
(await () => {
    while(true) {
        let [val, ch] = await Channel.select([a,b, Channel.timeout(1)]);
        if (val === undefined) break;
        // do something
        await Channel.timeout(16);
    }
})();
```

Other ideas I've already semi-tried and might re-integrate:

1) use an exponentially increasing delay over time. i.e. double the delay between polling rounds every few rounds (up to a maximum period, of course :)
2) use a `select` internal promise to handle the polling and then once a value is read (or an input closed) resolve the main promise. In my earlier tests this didn't seem to show much lower CPU usage though and the current implementation is more simple... will look into it again asap

**Comment by pedroteixeira** [comment]
Thinking about experimenting a different approach without select for my case here with "merge":
```ts
export function mergeChannels(chans: Array<Channel<any>>, out?: Channel<any>, close = true, named = false) {
  out = out || new Channel<any>();
  chans.forEach(inChannel => {
    inChannel.consume(x => {
      if (out.isClosed()) {
        return inChannel.close();
      }
      return out.write(named ? [inChannel.id, x] : x);
    });
  });
  return out;
}
``` 

One frequent doubt I have is how best handle when channels are closed.. Sometimes it feels odd only handling `isClosed` only in a future write.
