### ISSUE TITLE
[hdom] discussion: types for components

### ISSUE THREAD

**Issue by acarabott** [thi-ng/umbrella#184]
I've been experimenting with ways to get types for components in the hdom tree, as if parameters change there is no warning when using the array syntax, e.g.

Component:
```ts
const nameCmp = (ctx: any, name: string) => ["div", name];
```

Usage
```ts
[nameCmp, "Karsten"]
```

The ideal type for this would be `[typeof nameCmp, string]` but this is a pain to export for every component.
You can get the types of a parameters of a function using `Parameters<T>` but this returns a tuple, not an array, so you can't do a spread.

The best I've come up with is:

```ts
export type Cmp<T extends (...args: any) => void> =
  | [T]
  | [T, Parameters<T>[1]]
  | [T, Parameters<T>[1], Parameters<T>[2]]
  | [T, Parameters<T>[1], Parameters<T>[2], Parameters<T>[3]]
  | [T, Parameters<T>[1], Parameters<T>[2], Parameters<T>[3], Parameters<T>[4];
```
 (abbreviated, but could have up to N parameters)

Usage:
```ts
[nameCmp, "Karsten"] as Cmp<typeof nameCmp>
```

This ensures your parameters are of the correct types, but doesn't check you've supplied enough parameters. Anyone got another solution?

**Comment by postspectacular** [comment]
Hi @acarabott - I'd agree w/ what @nkint has already reposted to you in Discord, i.e. that if you really do require fully type checked components, I'd recommend to **not** use the array embedding syntax for child components, but use direct function calls. If your components don't make use of the hdom user context object (most probably don't), you can also skip that first arg. There're no negative side effects (I can think of) to doing that, just a different call style...

**Comment by acarabott** [comment]
Ah, For some reason I was under the impression there was a caching/performance benefit to the array syntax. Yeah the function call approach solves the problem.

**Comment by postspectacular** [comment]
@acarabott there're some benefits for some components, but - in the current state - the main difference is only more or less stylistic. The array syntax is more uniform and the component functions are executed during tree normalization (just before diffing). There's still scope (and the original plan was) to defer their evaluation until **after** diffing, but I haven't got around implementing that thus far. In theory, given this component function:

```ts
import { repeatedly } from "@thi.ng/transducers";

const grid = (ctx: any, cols: number, rows: number) =>
  ["div", repeatedly(()=> ["div.row", repeatedly(() => ["div.cell"], cols)], rows)];
```
...and these 2 trees:
```ts
// previous tree
[grid, 10, 10]

// current
[grid, 10, 11]
```

If the evaluation of `grid` would be delayed until *after* diffing, this would be *much* faster than it is currently the case or if you'd call `grid(null, 10, 10)` directly: Basically, the diff would only need to compare a 3-element array vs. a nested array of 100 children...

However, to achieve that behavior requires a pretty drastic refactoring and interleaving of what are currently 2 separate processing phases: first tree normalization and then diffing. The new approach   would have to perform incremental normalization from within the recursive diffing stage. I've tried that once before, but gave up due to time constraints and TBH I think hdom is fast enough in the current form for all the apps I've built w/ it thus far. Still, it'd be awesome to implement this at some point...

**Comment by postspectacular** [comment]
The other aspect I forgot to mention with the above is that this would preclude using/allowing components with local state, since their diff would now purely depend on given arguments. I'm not sure if that restriction would be really desirable...
