### ISSUE TITLE
[transducers] how to use group by?

### ISSUE THREAD

**Issue by hyusetiawan** [thi-ng/umbrella#212]
high level question
- can I use transducer functions to replicate SQL queries? in my mind it can, but just for sanity check, this is not an insane attempt yeah?
- I am having trouble replicating group by queries such as `SELECT COUNT(CustomerID), Country
FROM Customers
GROUP BY Country;` I see that there is a groupbyobj, but can I see an example?

**Comment by postspectacular** [comment]
Hi @hyusetiawan - sorry for the delay, of course there's the possibility to translate at least a subset of SQL to the transducer model/workflow, but don't expect it to map 100%. Also, not all queries can be succinctly expressed with a single `transduce()` and more complex ones might/will require multiple stages of processing (just like with any SQL implementation internally too).

I've put up some examples here: https://codesandbox.io/s/transducer-queries-8rzk0

This includes your example query and another one which uses a table join...

**Comment by hyusetiawan** [comment]
@postspectacular  thank you for taking the time to answer my question, I knew, in the end, is so simple! I ended up moving on to rxjs actually, a piece of user feedback from me: 

thi.ng has exactly everything I need, transducer + stream + fsm, but I have not been able to be productive in the 2 days I spent to evaluate it. I ended up reading the source code to reverse engineer what it does which was difficult because I am very new to streams in general. Using rxjs, I have access to a wealth of docs and more online, which is highly crucial for people to get into streams to make that mental model switch from imperative.

I wonder if it's a good growth hack to have an rxjs compatibility package, so a developer can use the same rxjs API with thi-ng underneath thus leveraging their docs + rxviz / tooling, etc

**Comment by postspectacular** [comment]
@hyusetiawan - thank you for the honest feedback & am sorry you found it all hard to get going with... This project still largely being developed by a single person (w/ occasional contributions from others), simply can't compete with the plethora of social infrastructure of much larger projects like rx. But, one has to start somewhere...

Also, if I may ask you in return: the [rstream readme](https://github.com/thi-ng/umbrella/blob/develop/packages/rstream/README.md) contains a wealth of information (incl. marble diagrams) and links to rstream example projects - doesn't any of this help you at all to get going? In the future, you might also get answers faster by asking questions in [our Discord community](https://discord.gg/JhYcmBw). I'm always open for ideas to improve docs and regularly dedicate time to that aim... I'm sometimes very stumped by such feedback, since I think the most important packages in this repo have quite detailed documentation, but yet somehow seemingly isn't sufficient/useful. Any more detailed feedback from a first tine user is highly appreciated!!!

As for your last point, I certainly understand the sentiment/desire, but I don't think an rx compatibility package is a realistic undertaking (at least not from my perspective): a) I don't have the bandwidth to develop and maintain such a layer and b) rstream doesn't just provide a different syntax for rx observables, there other conceptual differences and so I'm not quite sure what the overall aim for such a "compatibility layer" would be? It seems a little brittle from the start, trying to provide the illusion for users to work with rx, but actually using somewhat different semantics under the hood. Additionally, such a layer would somewhat defeat the explicit separation of concerns provided by "outsourcing" all kinds of stream transformations to transducers, which can equally applied to other sequential data sources. Rx has a huge API surface because it provides all sorts of operations specifically for observables. The rstream API is much smaller and largely relies on transducer composition to transform streams...

**Comment by hyusetiawan** [comment]
@postspectacular  oh please don't be sorry :) I think for people who are already familiar with reactive programming it should be very familiar to the, as I am starting to see similarities between the libraries.

yeah, I read through all of that, the guides are pretty high level for a noob like me so when I am about to start the actual development work, I am not sure where to start. So to solve my problem, I dug through specific examples and found some of them are missing which made me think "is this the missing operator that would help me", example: just by the function name groupByObj, I thought that this is definitely the answer to my join problem but this is the link to the guide: [https://github.com/thi-ng/umbrella/blob/develop/packages/transducers/src/rfn/group-by-obj.ts](groupByObj), looks like I have to reverse engineer the source code. Some of the other functions do have examples + explanations at the top though. 

You should put the discord channel in the readmes that sounds like a great resource, and I want to point out that the repeated image screenshots in almost all of the readme are not as helpful, I suggest putting a DEMO link where users can browse on their own, the purpose of the docs, in my opinion, is to be a reference, not a showcase.

The aim of the compatibility layer is to piggyback on the wealth of documentation that rxjs has, a good example would be: if thi.ng has rxjs'  [https://rxjs.dev/api/operators/groupBy](groupBy), which in the end it's an operator that still uses thi.ng primitives underneath. Given that I could use their detailed docs + [youtube videos](https://www.youtube.com/watch?v=hsr4ArAsOL4&t=10m4s) to know how it works and at the same time, I'll still be interfacing with the rest of the ecosystem, that is transducers, FSM, the graph, atom and more. This is more or less, a growth hack.

I want to say though that your work is here genuinely impressive, curious how are you able to create such a huge library by yourself? I was under the impression this is auto-generated somehow from clojure, turns out it's a work of one mad man :D
