### ISSUE TITLE
[webgl] Debug option for `console.log` in `defShader`?

### ISSUE THREAD

**Issue by stwind** [thi-ng/umbrella#217]
`defShader` [prints](https://github.com/thi-ng/umbrella/blob/develop/packages/webgl/src/shader.ts#L196) the compiled programs in console. When working with multiple shaders I found the console logs a bit consufing. Would it be a good idea to add an option toggling this feature? something like:

```javascript
defShader(gl, spec, { debug: true })
```

**Comment by postspectacular** [comment]
Hey @stwind - thank you, this was an oversight/leftover effect from older times. I'd already switched the package to using a configurable logger rather than plain `console.log`, but forgot to update this call site...

For future reference (should create a wiki page for this) to enable/configure logging for this and other packages, do:

```ts
import { ConsoleLogger, LogLevel } from "@thi.ng/api";
import { setLogger } from "@thi.ng/webgl";

setLogger(new ConsoleLogger("webgl", LogLevel.DEBUG));
```

By default only a [`NullLogger`](https://github.com/thi-ng/umbrella/blob/develop/packages/api/src/logger.ts#L4) is used, so you'll not see any output now, regardless of severity. There're other uses in the webgl pkg where also warnings are logged (e.g. invalid uniforms etc.), so if you just want to see those, use the above snippet w/ `LogLevel.WARN`...

**Comment by postspectacular** [comment]
Added wiki page with further details: [Package specific logger configuration](https://github.com/thi-ng/umbrella/wiki/Package-specific-logger-configuration)

Hth!

**Comment by postspectacular** [comment]
@stwind Btw. Will do another release tonight...

**Comment by stwind** [comment]
@postspectacular Awesome! Thanks!

**Comment by postspectacular** [comment]
@stwind v1.0.4 now available :)
