### ISSUE TITLE
[shader-ast-stdlib] Uncaught TypeError: env.vec3v is not a function

### ISSUE THREAD

**Issue by stwind** [thi-ng/umbrella#250]
The [shader-ast-workers](https://github.com/thi-ng/umbrella/tree/develop/examples/shader-ast-workers) demo shows the following errors

```
Uncaught TypeError: env.vec3v is not a function
    at raymarchDir (eval at compile (worker.js:1), <anonymous>:124:27)
    at mainImage (eval at compile (worker.js:1), <anonymous>:145:95)
    at worker.js:1
    at oh (worker.js:1)
    at worker.js:1
    at r (worker.js:1)
    at worker.js:1
```

Got no idea where `vec3v` comes from, probably somewhere in `shader-ast-js`?

**Comment by postspectacular** [comment]
Thanks @stwind - I'm not quite sure what happened there, but the local version of the demo in the current `develop` branch works and I must have uploaded the demo last during the recent round of updates/refactoring of the shader-ast packages (there were some missing (b/i)vec2/3/4 coercions which I added last month, but not sure where that error in the demo came from, must have been temporary). Just re-uploaded current version and can confirm the issue is fixed.

**Comment by postspectacular** [comment]
(ps. might have to wait a few mins for cloudfront cache invalidation to complete, still seeing old version...)
