### ISSUE TITLE
Incorrect typings for Heap#peek

### ISSUE THREAD

**Issue by Jannis** [thi-ng/umbrella#283]
The documentation and TypeScript types for `Heap#peek` say that it always returns `T`. However, the current implementation returns `T | undefined` due to it's `return this.values[0]` implementation:

Code: https://github.com/thi-ng/umbrella/blob/8fed74edc94bfb65f84e8982e6724619bbfbd1d0/packages/heaps/src/heap.ts#L79-L81
Docs: https://docs.thi.ng/umbrella/heaps/classes/_heap_.heap.html#peek

An empty `Heap` or `DHeap` would return `undefined` because `emptyArray[0]` is undefined.

My suggestion would be to either make `peek` return `T | undefined` (preferred due to its better developer ergonomics) or make it throw an exception if there are no values (less preferred), and potentially be more explicit in the documentation.

**Comment by gavinpc-mindgrub** [comment]
Related: [`--noUncheckedIndexedAccess`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#checked-indexed-accesses-nouncheckedindexedaccess).

Haven't used that myself yet -- I imagine it's pretty breaky.  But here, the unsafe signature is leaking into the API, so maybe something to consider.

**Comment by postspectacular** [comment]
Thanks @Jannis - I'd say the intention here definitely is `T | undefined` rather than throwing an error (same as `Array.peek()` contract). There're other parts/packages in umbrella where you _will_ get an `OutOfBoundsError`, but in those case it's (IMHO) more justified & useful than doing so here. So we're on same page :)

@gavinpc-mindgrub thank you for that option, didn't know about that either, but will check it out!

**Comment by Jannis** [comment]
@postspectacular Awesome, thanks for the quick turnaround!

**Comment by postspectacular** [comment]
@Jannis Hah! Don't get used to it :) Will try to do a new release tomorrow...

**Comment by postspectacular** [comment]
Just pushed a new release! ([changelog](https://github.com/thi-ng/umbrella/blob/develop/packages/heaps/CHANGELOG.md#1238-2021-03-17)) 🎉
