### ISSUE TITLE
[transducers-stats] Supported indicators MACD

### ISSUE THREAD

**Issue by sy92th** [thi-ng/umbrella#31]
Is the library supporting the MACD indicators?
If not, can indicators be made soon?

**Comment by postspectacular** [comment]
Added and released as v0.3.0 😄

**Comment by postspectacular** [comment]
Please use v0.3.1 instead...

**Comment by sy92th** [comment]
I use version "^0.3.1"


```
const chartDataMACD = Array.from(tx.iterator(stats.macd(fastPeriod, slowPeriod, signalPeriod), closeArray));
console.log('Length MACD: '+chartDataMACD.length);
console.log('Length data: 'closeArray.length);
```

result (with fast: 12, slow: 26, smooth: 9):
Length MACD: 52252
Length data: 52285 (expected: 52252 +26 -1 = 52277)

Can you check this problem? I think the MACD is being miscalculated.

**Comment by postspectacular** [comment]
Hey @sy92th - did you read the docs?

https://github.com/thi-ng/umbrella/blob/master/packages/transducers-stats/src/macd.ts#L34

You didn't take into account the 2nd moving average `smooth` applied to difference between the `fast` and `slow` ones. That's why the total lag of the indicator is `slow + smooth - 2`...
 
52285-(26+9-2) = 52252

**Comment by postspectacular** [comment]
Also see here: https://en.wikipedia.org/wiki/MACD#/media/File:MACDpicwiki.gif

**Comment by sy92th** [comment]
Ahh I'm wrong. So sorry
