### ISSUE TITLE
[transducers-stats] Build fail with UglifyJSPlugin (Webpack)

### ISSUE THREAD

**Issue by sy92th** [thi-ng/umbrella#32]
It all works fine with dev, but when you build the production:
```
ERROR in app/vendor.e8d8a5c89728897d6c01.bundle.js from UglifyJs
Unexpected token: name (r) [app/vendor.e8d8a5c89728897d6c01.bundle.js:1,302965]
```

**Comment by postspectacular** [comment]
I'm assuming you're using an older version of webpack, since more recent ones (currently v4.16.3) do properly support ES6 syntax features and don't require the UglifyJS plugin anymore. That plugin doesn't support ES6 syntax, hence the error. If you do require ES5, you'll currently need to transpile this yourself, since all packages in the project are emitted only in ES6 syntax (in CommonJS format). Please also see #23.

However, I also do recommend taking a look at the [crypto chart example](https://github.com/thi-ng/umbrella/tree/master/examples/crypto-chart), which uses the transducer-stats package and has a webpack config and build command (in `package.json`) producing minified versions successfully (out of the box w/o plugins).

**Comment by sy92th** [comment]
OK thank @postspectacular . I use webpack version 3.6.0
I solved this problem with babel-loader (convert ES6 to ES5).
