### ISSUE TITLE
[wasm-api-dom] allocating before calling createElement may cause a DOMException

### ISSUE THREAD

**Issue by MarcusWagberg** [thi-ng/umbrella#359]
The following code causes a DOMException: String contains an invalid character.
```zig
const std = @import("std");
const wasm = @import("wasmapi");
const dom = @import("dom");

pub usingnamespace wasm;

var gpa = std.heap.GeneralPurposeAllocator(.{}){};
pub var WASM_ALLOCATOR = gpa.allocator();

export fn start() void {
    dom.init(WASM_ALLOCATOR) catch |e| @panic(@errorName(e));
    _ = WASM_ALLOCATOR.alloc(u8, 1024) catch |e| @panic(@errorName(e));
    _ = dom.createElement(&.{
        .tag = "div",
        .parent = 0,
    });
}
```
This exception is caused by tagName in following function dereferencing an invalid WasmStringSlice.
https://github.com/thi-ng/umbrella/blob/078df7912aa4a1120084627b088fd5a3d2946b80/packages/wasm-api-dom/src/dom.ts#L56-L62

I prusume this is caused by the allocation needing to grow the memory which leads the WasmStringSlice to become invalid. Adding `this.parent.ensureMemory();` to createElement dose seem to fix this.

**Comment by postspectacular** [comment]
Oh, thank you - I thought I'd covered all cases for `ensureMemory()`, but missed that one! Since the check for memory validity is very cheap, it's probably safest to just add it to the [`WasmStringSlice`](https://github.com/thi-ng/umbrella/blob/develop/packages/wasm-api/src/string.ts#L9) ctor & accessors (and same for `WasmStringPtr`). After some debugging I can see the issue is already in that string slice constructor, i.e. when obtaining the initial slice length... I'm doing more work on both the WASM core & dom packages & will push a fix later today... Thank you very much though!

**Comment by MarcusWagberg** [comment]
@postspectacular another thing i've recently found is that, the include directory seems to be missing from the files list in package.json for the wasm-api-dom package. Maybe you can include a fix for this also.

**Comment by postspectacular** [comment]
@MarcusWagberg - I've just published new versions of all `wasm-api-*` packages and the DOM package has also received major updates (main highlight: createElement() now supports optional attrib & event listener declarations too. Take a look at the new & updated Zig examples, much less boilerplate... :)

**Comment by MarcusWagberg** [comment]
@postspectacular - Great, i'll check it out whenever i get some time, have been busy with school the last couple of weeks.

**Comment by MarcusWagberg** [comment]
@postspectacular - I finally got some time to check out the new versions of the wasm-api packages and i am happy to report that, this issue is now fixed.

**Comment by MarcusWagberg** [comment]
@postspectacular - Also merry christmas in a week.
