### ISSUE TITLE
[errors] `UMBRELLA_ASSERTS` breaking skypack CDN imports

### ISSUE THREAD

**Issue by stwind** [thi-ng/umbrella#361]
The new [`UMBRELLA_ASSERTS`](https://github.com/thi-ng/umbrella/tree/develop/packages/errors#environment-variables) environment variable seems not recognized by skypack's build system, thus breaking its imports. [Here](https://codepen.io/stwind/pen/ZERGOoW) is a demo, using `<script type="module" src="https://cdn.skypack.dev/@thi.ng/errors"></script>` results in 

```
TypeError: undefined is not an object (evaluating 'process.env.UMBRELLA_ASSERTS')
```

looks like `process` is defined but not `process.env`, maybe adding another check for that or there is some way to work around?

**Comment by postspectacular** [comment]
Ohh.. thank you @stwind! This env var is actually not new and the issue is a regression of a recent update from a month ago when I got rid of the obsolete snowpack (not skypack!) env var logic: 781470d92b0a9aa6fe4a93935bd346a7fd4fc4fc

I've been testing this new logic with Vite, however should also have checked skypack, which seems to transpile this module to a different result & injects stuff not present in the original code... I will push an update in a minute, but we can only check if that works after the next release. Btw. the same issue also applies to `@thi.ng/expose`: 9a98c3e3b4ce93b765d1ca18bc16b70bc53eaa20

**Comment by postspectacular** [comment]
So I just pushed v2.2.3 ([changelog](https://github.com/thi-ng/umbrella/blob/develop/packages/errors/CHANGELOG.md#223-2022-10-28)) and it seems to have fixed the issue. Once I hear back from you with confirmation I will apply same fix for the `thi.ng/expose` package... 👍

**Comment by stwind** [comment]
Thanks @toxi, it works fine now, also check some other dependents like `@thi.ng/vectors` and they are working. Yeah I think you can push the same to `@thi.ng/expose`

**Comment by postspectacular** [comment]
Amazing & will do! Thank you again, as always!

**Comment by postspectacular** [comment]
Okay, fixed & released the expose pkg too now!
