### ISSUE TITLE
[hiccup, hdom](examples/commit-table-ssr) - react-like hydrate?

### ISSUE THREAD

**Issue by den1k** [thi-ng/umbrella#39]
Just got around to reading the code and it looks like the browser and SSR version are separate in the sense that unlike [react's hydrate](https://reactjs.org/docs/react-dom.html#hydrate) we get either one or the other but not the best of both worlds. `hydrate` is what I meant to express (admittedly, through a handshake emoji) in [this tweet](https://twitter.com/denik/status/1033406896680706049).

Is there a _hydration_ story for hiccup / hdom?

**Comment by postspectacular** [comment]
Fundamentally, yes there is, but you must understand that hdom is not like react because hdom **never** diffs against the real DOM, but only against another hdom tree/array. So in a way hydrate already is there, but the `updateUI()` transducer doesn't currently support it as it always assumes an empty initial DOM state (under the chosen root element). It's trivial to add a `hydrate` flag though, and if enabled would simply need to skip diffing the very first received tree.

There's one other difference which needs to be taken care of: @thi.ng/hiccup doesn't wrap text nodes in `<span>` whereas hdom does by default (in order to better diff them). So I'd need to add an option for the server code to emit these too or else there will be inconsistencies when mutating the DOM.

But other than those 2 small things it should just work...

**Comment by postspectacular** [comment]
Actually, reading more about react's hydrate, the above is not sufficient :( The first client tree would still need to be processed (partially at least) to attach missing event handlers, that would be not be too hard either though...

**Comment by postspectacular** [comment]
So I've just updated `hiccup`, `hdom` & `transducers-hdom` to support hydration more clearly & directly and pushed `@thi.ng/hdom@4.0.0` (major version change due to other breaking API changes). I've also created a [new example](https://github.com/thi-ng/umbrella/tree/master/examples/hydrate-basics/) to better test this. Updating the `commit-table-ssr` demo will take me a bit longer...

Also see:
https://github.com/thi-ng/umbrella/blob/master/packages/hdom/src/dom.ts#L58
https://github.com/thi-ng/umbrella/blob/master/packages/hdom/src/start.ts#L29

**Comment by den1k** [comment]
Great. Digging in!

**Comment by postspectacular** [comment]
Closing this for now. Please open a new issue if you run into any probs with `hydrateDOM`...
