### ISSUE TITLE
RDMS based on rstream-query

### ISSUE THREAD

**Issue by ansarizafar** [thi-ng/umbrella#453]
In 2024 developers are still forced to use decades old RDMS like Postgres with SQL  rstream-query is amazing, Why not build a Full-fledged database based on rstream-query?

**Comment by postspectacular** [comment]
Thank you @ansarizafar — the main reason is that there's _a lot_ more to building a reliable & scalable database than what this package offers. I'm not saying it's not worth it to extend it — I sometimes do — but in general, I just don't see the need, since there're already some related DBs which are using a similar SPARQL/Datalog inspired approach, incl. various well established, mature RDF/Linked Data triple-stores, as well as Datomic & XTDB... For most of my uses, these are overblown solutions, and I've also got a related earlier project which does also offer a REST endpoint for queries: https://thi.ng/fabric

Hth!
