### ISSUE TITLE
[rstream-gestures] normalize mousewheel delta

### ISSUE THREAD

**Issue by postspectacular** [thi-ng/umbrella#71]
Have received reports that mousewheel zoom handling on Windows is semi-broken / too abrupt. Should implement / reuse [something like this](https://stackoverflow.com/a/30134826/294515) to normalize behavior across browsers/platforms...

cc @acarabott

**Comment by acarabott** [comment]
Working on an update to rstream-gestures atm, will try implementing this!

**Comment by acarabott** [comment]
I've put together a demo of a new version of rstream-gesture that includes the facebook technique, although it normalizes browsers rather than OSes... 

Testing with Parallels it feels the same between Chrome on Mac and Windows, but Firefox is slow on Parallels so it's hard to compare. I don't have a real Windows install to test with...

https://github.com/acarabott/umbrella-rstream-gesture

I haven't updated documentation yet, but the example is functional.

**Comment by postspectacular** [comment]
thanks @acarabott !!! ⚡️ been away and will check out asap (in coming days)... you're not forgotten!

**Comment by acarabott** [comment]
👍 No worries! It took my long enough to get round to doing.

**Comment by postspectacular** [comment]
I'm pretty sure this is fixed by now :)
