### ISSUE TITLE
[thi.ng/vectors] heading for a segment

### ISSUE THREAD

**Issue by nkint** [thi-ng/umbrella#75]
Hi!
Sometimes I need to have the heading of a 2D line segment (befined by two points) as fast as possibile:

```
const headingSegment = (a , b) => Math.atan2(b[1] - a[1], b[0] - a[0])
```

Right now one possibile way to achieve this with existing packages could be:

```
const { direction, heading } = require( '@thi.ng/vectors')
heading(direction([], a, b), [0, 1])
```

But it requires a new array allocation for the `direction`.

Question: are there better ways to do it with existing package? Is it possibile to add it in `umbrella/packages/vectors/src/heading.ts`? In case, what would be a better name to have a non-confusing signature next the current ones?

**Comment by postspectacular** [comment]
I think that's a great idea & `headingSegment` is a good name for it. The current workaround using `direction()` is not great, since it also normalizes the direction vector, so you don't want to use this in this case...

i just released a new version of the package with these new fns:

https://github.com/thi-ng/umbrella/blob/master/packages/vectors/src/heading-segment.ts

Hth!

**Comment by nkint** [comment]
thanks!
